# config

filter_domains = '''
.163jiasu.com
.1test.cn
.21okglb.cn
.21vianet.com.cn
.21vokglb.cn
.360cdn.cn
.360qhcdn.com
.360wzb.cn
.360wzb.com
.51cdn.com
.5test.cn
.acadn.com
.afxcdn.net
.aicdn.com
.akadns.net
.akamai.
.akamai.com
.akamaiedge.net
.akamai.net
.akamai-staging.net
.akamaitech.net
.akamaitechnologies.com
.akamaized.net
.alicdn.com
.alicloudlayer.com
.alicloudsec.com
.alikunlun.com
.alikunlun.net
.alivecdn.com
.aliyuncs.com
.aliyun-inc.com
.amazonaws.com
.aodianyun.com
.aqb.so
.att-dsa.net
.awsdns
.ay1.b.yahoo.com
.azureedge.
.azureedge.net
.b2r.com.cn
.baiduyundns.cn
.baiduyundns.com
.baiduyundns.net
.bcedns.cn
.bcedns.com
.bcedns.net
.bdydns.cn
.bdydns.com
.bdydns.net
.bitgravity.
.bitgravity.com
.bluehatnetwork.com
.blueit.com
.blueit.org.cn
.bsclink.cn
.c3cache.net
.c3cdn.net
.cachecn.com
.cachecn.net
.cachefly.
.cachefly.net
.cap-mii.net
.cc-1.com
.ccbench.com
.cc-cps.cn
.cc-cps.com
.cc-cps.com.cn
.cc-cps.mobi
.cc-cps.net
.ccgslb.cn
.ccgslb.com
.ccgslb.com.cn
.ccgslb.net
.ccgslb.net.cn
.ccindex.cn
.ccindex.com.cn
.ccmplus.cn
.ccmplus.com.cn
.ccmplus.net
.cdn2cdn.net
.cdn77.net
.cdn77.org
.cdn.bitgravity.com
.cdn.cloudflare.net
.cdnetworks.net
.cdngc.net
.cdngslb.com
.cdnhwc2.com
.cdnify.io
.cdn.qshyy.cn
.cdnsun.net
.cdnsvc.cn
.cdnsvc.com
.cdnsvc.com.cn
.cdnsvc.net
.cdnsvc.net.cn
.cdn.telefonica.com
.cdntip.com
.cdnudns.com
.chinacache.com
.chinacache.com.cn
.chinacache.net
.chinacache.org
.chinacdnweb.qiniu.com
.chinaidns.net
.chinanetcenter.com
.clients.turbobytes.net
.cloudcdn.cn
.cloudcdn.net
.clouddn.com
.cloudflare
.cloudflare.com
.cloudfront.
.cloudfront.net
.cloudglb.com
.cloudglb.net
.cloudtcp.net
.cloudxns.com
.cloudxns.net
.cncssr.chinacache.net
.customcdn.cn
.customcdn.com
.dnion.com
.dnspao.com
.dnsv1.
.dnsv1.com
.dwion.com
.edgecast.
.edgecastcdn.net
.edgekey.
.edgekey.net
.edgesuite.net
.ewcache.com
.fastcache.com
.fastcdn.com
.fastly.
.fastlylb.net
.fastly.net
.fastwebcdn.com
.fastweb.com.cn
.ffdns.net
.footprint.
.footprint.net
.fpbns.
.fpbns.net
.fsspace.cn
.fsspace.com
.fsspace.com.cn
.fwcdn.com
.fwcdn.net
.fwdns.net
.fwmob.com
.gccdn.cn
.gccdn.net
.globalcdn.cn
.googlesyndication.
.googleusercontent.com
.gslbsvc.cn
.gslbsvc.com
.gslbsvc.com.cn
.gslbsvc.net
.gslbsvc.net.cn
.gslb.taobao.com
.gslb.tbcache.com
.hacdn.com
.hacdn.net
.hadns.net
.hd-cdn.com
.hdslb.com
.hdslb.net
.hiberniacdn.com
.hichina.com
.hichina.net
.hwcdn.net
.ialicdn.com
.igslb.net
.incapdns.
.incapdns.net
.inscname.net
.insnw.net
.instacontent.net
.jcloud-cdn.com
.jiashule.com
.jiasule.org
.jomodns.com
.ks-cdn1.com
.ksyuncdn.com
.kunlunaq.com
.kunlunar.com
.kunlunca.com
.kunluncan.com
.kunlun.com
.kunlunea.com
.kunlungem.com
.kunlungr.com
.kunlunhuf.com
.kunlunle.com
.kunlunli.com
.kunlunno.com
.kunlunpi.com
.kunlunra.com
.kunlunsa.com
.kunlunsc.com
.kunlunsl.com
.kunlunso.com
.kunlunta.com
.kunlunvi.com
.kunlunwe.com
.kxcdn.com
.l.doubleclick.net
.letvcdn.com
.lldns.net
.llnwd.
.llnwd.net
.lswcdn.net
.lxdns.com
.lxdns.net
.lxsvc.cn
.lxsvc.net
.mirror-image.net
.mncdn.com
.mschcdn.com
.mwcloudcdn.com
.myalicdn.com
.myxns.cn
.myxns.com.cn
.myxns.net.cn
.myxns.org
.netcenter.com.cn
.netdna.
.netdna-cdn.com
.netdna.com
.netdna-ssl.com
.newdefend.cn
.newdefend.com
.newdefend.com.cn
.newdefend.net
.newdefend.net.cn
.newdefend.org
.newdefend.org.cn
.ngenix.
.okglb.com
.ourglb0.com
.ourwebat.com
.ourwebcdn.com
.ourwebcdn.net
.ourwebpic.com
.panthercdn.com
.pilidns.com
.qbox.me
.qihucdn.com
.qingcdn.com
.qiniudn.com
.qiniudns.com
.rncdn1.com
.shifen.com
.simplecdn.net
.spcdntip.com
.spdydns.com
.speedcdns.com
.speedupchina.com
.speedupchina.net
.stackpathdns.com
.swiftcdn1.com
.swiftserve.com
.sz-dns.net
.tbcache.com
.tc.cdntip.com
.tcdn.qq.com
.tcloudscdn.com
.tdnsv8.com
.telefonica.
.tlgslb.com
.trpcdn.net
.txcdn.cn
.txnetworks.cn
.ucloud.cn
.unicache.com
.verycdn.net
.verygslb.com
.vo.llnwd.net
.vo.msecnd.net
.wangsu.com
.webluker.com
.wscdns.com
.wscloudcdn.com
.wsdvs.com
.wsglb0.com
.wsngb.com
.xgslb.net
.yunjiasu-cdn.net
.zenedge.net
.dns.com
'''.strip('\n').split('\n')


filter_hosts = '''
223.5.5.5
223.6.6.6
114.114.114.114
114.114.115.115
180.76.76.76
119.29.29.29
182.254.116.116
8.8.8.8
8.8.4.4
9.9.9.9
9.9.9.10
149.112.112.112
4.2.2.1
4.2.2.2
4.2.2.3
4.2.2.4
4.2.2.5
4.2.2.6
1.1.1.1
1.0.0.1
1.0.0.2
1.0.0.3
1.0.0.19
208.67.222.222
208.67.220.220
8.26.56.26
8.20.247.20
84.200.69.80
84.200.70.40
185.228.168.9
185.228.169.9
64.6.64.6
64.6.65.6
198.101.242.72
23.253.163.53
176.103.130.130
176.103.130.131
'''.strip('\n').split('\n')


top_sufix = 'cc|aero|arpa|asia|biz|cat|com|coop|edu|gov|int|info|jobs|mil|mobi|museum|name|net|org|pro|tel|trave|xxx|digital|run'

#cn_sufix = 'ac.cn|ah.cn|bj.cn|com.cn|cq.cn|fj.cn|gd.cn|gov.cn|gs.cn|gx.cn|gz.cn|ha.cn|hb.cn|he.cn|hi.cn|hk.cn|hl.cn|hn.cn|jl.cn|js.cn|jx.cn|ln.cn|mo.cn|net.cn|nm.cn|nx.cn|org.cn|edu.cn|'

# .ac|.ad|.ae|.af|.ag|.ai|.al|.am|.an|.ao|.aq|.ar|.as|.at|.au|.aw|.az|.ba|.bb|.bd|.be|.bf|.bg|.bh|.bi|.bj|.bm|.bn|.bo|.br|.bs|.bt|.bv|.bw|.by|.bz|.ca|.cc|.cd|.cf|.cg|.ch|.ci|.ck|.cl|.cm|.cn|.co|.cr|.cu|.cv|.cx|.cy|.cz|.de|.dj|.dk|.dm|.do|.dz|.ec|.ee|.eg|.eh|.er|.es|.et|.eu|.fi|.fj|.fk|.fm|.fo|.fr|.ga|.gd|.ge|.gf|.gg|.gh|.gi|.gl|.gm|.gn|.gp|.gq|.gr|.gs|.gt|.gu|.gw|.gy|.hk|.hm|.hn|.hr|.ht|.hu|.id|.ie|.il|.im|.in|.io|.iq|.ir|.is|.it|.je|.jm|.jo|.jp|.ke|.kg|.kh|.ki|.km|.kn|.kp|.kr|.kw|.ky|.kz|.la|.lb|.lc|.li|.lk|.lr|.ls|.lt|.lu|.lv|.ly|.ma|.mc|.md|.me|.mg|.mh|.mk|.ml|.mm|.mn|.mo|.mp|.mq|.mr|.ms|.mt|.mu|.mv|.mw|.mx|.my|.mz|.na|.nc|.ne|.nf|.ng|.ni|.nl|.no|.np|.nr|.nu|.nz|.om|.pa|.pe|.pf|.pg|.ph|.pk|.pl|.pm|.pn|.pr|.ps|.pt|.pw|.py|.qa|.re|.ro|.ru|.rw|.sa|.sb|.sc|.sd|.se|.sg|.sh|.si|.sj|.sk|.sl|.sm|.sn|.so|.sr|.st|.sv|.sy|.sz|.tc|.td|.tf|.tg|.th|.tj|.tk|.tl|.tm|.tn|.to|.tp|.tr|.tt|.tv|.tw|.tz|.ua|.ug|.uk|.um|.us|.uy|.uz|.va|.vc|.ve|.vg|.vi|.vn|.vu|.wf|.ws|.ye|.yr|.yt|.yu|.za|.zm|.zw
country_sufix = 'ac|ad|ae|af|ag|ai|al|am|an|ao|aq|ar|as|at|au|aw|az|ba|bb|bd|be|bf|bg|bh|bi|bj|bm|bn|bo|br|bs|bt|bv|bw|by|bz|ca|cc|cd|cf|cg|ch|ci|ck|cl|cm|cn|co|cr|cu|cv|cx|cy|cz|de|dj|dk|dm|do|dz|ec|ee|eg|eh|er|es|et|eu|fi|fj|fk|fm|fo|fr|ga|gd|ge|gf|gg|gh|gi|gl|gm|gn|gp|gq|gr|gs|gt|gu|gw|gy|hk|hm|hn|hr|ht|hu|id|ie|il|im|in|io|iq|ir|is|it|je|jm|jo|jp|ke|kg|kh|ki|km|kn|kp|kr|kw|ky|kz|la|lb|lc|li|lk|lr|ls|lt|lu|lv|ly|ma|mc|md|me|mg|mh|mk|ml|mm|mn|mo|mp|mq|mr|ms|mt|mu|mv|mw|mx|my|mz|na|nc|ne|nf|ng|ni|nl|no|np|nr|nu|nz|om|pa|pe|pf|pg|ph|pk|pl|pm|pn|pr|ps|pt|pw|py|qa|re|ro|ru|rw|sa|sb|sc|sd|se|sg|sh|si|sj|sk|sl|sm|sn|so|sr|st|sv|sy|sz|tc|td|tf|tg|th|tj|tk|tl|tm|tn|to|tp|tr|tt|tv|tw|tz|ua|ug|uk|um|us|uy|uz|va|vc|ve|vg|vi|vn|vu|wf|ws|ye|yr|yt|yu|za|zm|zw'

